version: '3.5'
services:
  keys-nezih:
    image: node-20-nest
    env_file:
      - .env
    container_name: 'keys-nezih'
    working_dir: /app
    command: ['tail', '-f', '/dev/null']
    ports:
      - '0.0.0.0:3000:3000'
    networks:
      - hostglobal
    volumes:
      - '.:/app'

networks:
  hostglobal:
    external:
      name: hostglobal
